stages:
  - build
  - test
  - deploy

image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - apt-get update
  - apt-get install -y docker.io
  - docker info
  - docker-compose --version
  - docker build -t my-image .

build:
  stage: build
  tags: 
    - docker 
    - linux 
    - nodejs
  script:
    - docker-compose build --no-cache

test:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose exec service1 npm install
    - docker-compose exec service1 npm test
    - docker-compose exec service2 npm install
    - docker-compose exec service2 npm run test
  after_script:
    - docker-compose down

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - main

