stages: 
  - build 
  - test 
  - deploy 
 
image: docker/compose:latest
 
services: 
  - docker:dind 
 
variables: 
  DOCKER_DRIVER: overlay2 
  DOCKER_TLS_CERTDIR: ""
  NODE_ENV: ci
 
before_script: 
  - docker info 
  - docker-compose --version

 
build: 
  stage: build 
  tags:  
    - docker  
    - linux  
    - nodejs 
  script: 
    - docker-compose build --no-cache 

test: 
  stage: test 
  script: 
    - docker-compose up -d
    - docker-compose exec -T service1 npm install 
    - docker-compose exec -T service1 npm test 
  
  after_script: 
    - docker-compose down

deploy: 
  stage: deploy 
  script: 
    - docker-compose up -d 
  only: 
    - main