version: '3.8'

services:
  nginx:
    build: .
    image: nginx-image
    ports:
      - "8198:8198"
      - "8197:8197"
    depends_on:
      - service1
    networks:
      - ridvanContainer
        
  service1:
    build: ./Service1
    image: exposed_to_outside_service1_image.v1
    expose:
      - "8199"
    depends_on:
      - service2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ridvanContainer
    environment:
      - HOSTNAME=service1
    deploy:
      replicas: 3  
    labels: 
      - "service=sexposed_to_outside_service1.v1"
    
  service2:
    build: ./Service2
    image: internal_service2_image.v1
    container_name: internal_service2.v1
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ridvanContainer
    expose:
      - 8199 #exposed only internally
    environment:
      - HOSTNAME=internal_service2.v1
networks:
  ridvanContainer:
    driver: bridge
