version: '3.8'

services:
  nginx:
    build: ./nginx
    image: nginx-image
    ports:
      - "8198:8198"
      - "8197:8197" #Expose port 8197, this is an addition to nginx conf for the API gateway
    depends_on:
      - service1
    networks:
      - ridvanContainer
        
  service1:
    build: ./Service1
    image: exposed_to_outside_service1_image.v1
    expose:
      - "8199"
    depends_on:
      - service2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ridvanContainer
    environment:
      - HOSTNAME=service1
      - NODE_ENV=local
    deploy:
      replicas: 1  #normally creates 3 replicas but with state maangment, I used Redis but it took me a lot of time and I gave up on it
    labels: 
      - "service=sexposed_to_outside_service1.v1"
    
  service2:
    build: ./Service2
    image: internal_service2_image.v1
    container_name: internal_service2.v1
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ridvanContainer
    expose:
      - 8199 #exposed only internally
    environment:
      - HOSTNAME=internal_service2.v1
      - NODE_ENV=local
networks:
  ridvanContainer:
    driver: bridge
