version: '3'
services:
  service1:
    build: ./Service1
    image: exposed_to_outside_service1_image.v1
    container_name: exposed_to_outside_service1.v1
    ports:
      - "8199:8199"
    depends_on:
      - service2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ridvanContainer
   # hostname: service1_hostname
    environment:
      - HOSTNAME=exposed_to_outside_service1.v1
  service2:
    build: ./Service2
    image: internal_service2_image.v1
    container_name: internal_service2.v1
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ridvanContainer
    expose:
      - 8199 #eposed only internally
    #hostname: service2_hostname
    environment:
      - HOSTNAME=internal_service2.v1
networks:
  ridvanContainer:
    name: COMPSE140_custom_network

